### PR TITLE
Replace password by OAuth token

### PR DESCRIPTION
**Pull request by TimWolla**

### CODE REVIEW

**Comment by TimWolla** [comment]
You should change the password now, this will break existing „connections“, but should be better than GitHub shutting down that account :+1:

**Comment by TimWolla** [comment]
Oh, I see: The OAuth-Token does not work: oauth_authorization.destroy – Personal access token (API) deleted automatically (found in a public repository)

**Comment by VoidWhisperer** [comment]
Couldn't this be fixed by appending some random character into spots of the token then removing them before connecting? IE Splitting the token with a |?

**Comment by enzanki-ars** [comment]
The oauth token should be in a different file/environment variable, not public in any form.

**Pull request merged**
